Repository edunota/edunota-database, pull requests merged in 2023-09, with the labels that each got.

#7 Migration file fixed
  migrations/20230915234055_create_user_table.sql
Labels: enhancement, fix

#8 spindown command added
  .gitignore
  makefile.example
  readme.md
Labels: enhancement, good first issue, fix

#6 fix syntax on makefile
  makefile.example
Labels: good first issue, fix
